language: node_js
node_js:
  - "0.8"
before_install:
  - npm install -g grunt-cli

  - phantomjs --version

  - wget http://phantomjs.googlecode.com/files/phantomjs-1.8.1-linux-i686.tar.bz2
  - tar -xf phantomjs-1.8.1-linux-i686.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.8.1-linux-i686.tar.bz2 /usr/local/phantomjs

  - wget -nv https://github.com/n1k0/casperjs/archive/1.0.zip
  - unzip -q 1.0
  - sudo ln -s `pwd`/n1k0-casperjs-*/bin/casperjs /usr/local/bin/casperjs
